import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const P = await (await b.newContext({ viewport: { width: 1300, height: 900 } })).newPage(); const errs = [];
P.on('pageerror', e => errs.push(e.message));
await P.goto('http://localhost:8099/new/index.html'); await P.waitForTimeout(2000);
await P.evaluate(() => { window.print = () => { window.__printed = (window.__printed || 0) + 1; }; });
await P.evaluate(() => go('#/invoice/' + S.invoices[0].id)); await P.waitForTimeout(700);
await P.evaluate(() => printDoc('invoice', ED.doc)); await P.waitForTimeout(1200);
const r = await P.evaluate(() => { const el = document.getElementById('printRoot'); const box = el.getBoundingClientRect(); return { printed: window.__printed, hasDoc: !!el.querySelector('.bdoc'), display: getComputedStyle(el).display, h: box.height }; });
console.log('on screen after print:', JSON.stringify(r));
await P.evaluate(() => go('#/dashboard')); await P.waitForTimeout(600);
const tall = await P.evaluate(() => document.getElementById('printRoot').getBoundingClientRect().height);
await P.screenshot({ path: '/tmp/pgt/l2/shots/printroot-dashboard.png', fullPage: true });
await P.emulateMedia({ media: 'print' });
const pr = await P.evaluate(() => { const el = document.getElementById('printRoot'); return { display: getComputedStyle(el).display, h: el.getBoundingClientRect().height }; });
console.log('dashboard printRoot height on screen:', tall, '| print media:', JSON.stringify(pr));
await P.emulateMedia({ media: 'screen' });
await P.evaluate(() => window.dispatchEvent(new Event('afterprint')));
console.log('after afterprint, emptied:', await P.evaluate(() => document.getElementById('printRoot').innerHTML === ''), 'errors:', JSON.stringify(errs));
await b.close();
