import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const errs = []; let pass = 0, fail = 0;
const ok = (c, m, x) => { if (c) { pass++; console.log('  ok  ', m); } else { fail++; console.log('  FAIL', m, x !== undefined ? JSON.stringify(x).slice(0, 300) : ''); } };
const P = await (await b.newContext({ viewport: { width: 1300, height: 900 } })).newPage();
P.on('pageerror', e => errs.push(e.message)); P.on('console', m => { if (m.type() === 'error' && !/404|Failed to load/.test(m.text())) errs.push(m.text()); });
await P.goto('http://localhost:8099/new/index.html'); await P.waitForTimeout(2200);
const ev = (f, a) => P.evaluate(f, a);
console.log('\nOther income');
ok(await ev(() => APP_VERSION === '3.5.0' && Array.isArray(S.incomes) && S.settings.lists.incomeCategory.includes('Scrap sale')), 'v3.5, incomes collection + income types list');
const nav = await ev(() => [...document.querySelectorAll('#nav .nav-item')].map(a => a.textContent.trim()));
ok(nav.some(n => /Other income/.test(n)), 'menu: Finance → Other income');
const mk = await ev(() => monthKey(today()));
const before = await ev(mk => { const r = monthData(mk); return { np: r.np, col: r.collected, vat: r.sales.vat - r.expVat, cash: r.cashExpected }; }, mk);
await ev(() => go('#/incomes')); await P.waitForTimeout(500);
ok(/Other income/.test(await P.textContent('#view')), 'page opens');
await ev(() => editIncome()); await P.waitForTimeout(400);
await P.screenshot({ path: '/tmp/pgt/l2/shots/v35-income-form.png' });
await ev(async () => {
  await save('incomes', { date: today(), category: 'Scrap sale', description: '350 kg scrap metal', amount: 1050, vat: 50, cost: 0, receivedFrom: 'Al Sajaa Scrap', method: 'Cash' });
  await save('incomes', { date: today(), category: 'Car sale', description: '2015 Nissan Sunny', amount: 18000, vat: 0, cost: 15500, receivedFrom: 'Walk-in buyer', method: 'Bank transfer – WIO' });
  closeAllModals(); render();
}); await P.waitForTimeout(600);
const txt = await P.textContent('#view');
ok(/350 kg scrap metal/.test(txt) && /2015 Nissan Sunny/.test(txt), 'both incomes listed');
ok(/3,500\.00/.test(txt), 'profit total = 1000 (scrap after VAT) + 2500 (car after cost) = 3,500', txt.match(/Profit[^0-9]*([\d,.]+)/));
await P.screenshot({ path: '/tmp/pgt/l2/shots/v35-income.png' });
const after = await ev(mk => { const r = monthData(mk); return { np: r.np, col: r.collected, vat: r.sales.vat + r.oth.vat - r.expVat, cash: r.cashExpected }; }, mk);
ok(Math.abs(after.np - before.np - 3500) < 0.01, 'month-end net profit +3,500', { before, after });
ok(Math.abs(after.col - before.col - 19050) < 0.01, 'collected +19,050 (all money received)');
ok(Math.abs(after.vat - before.vat - 50) < 0.01, 'VAT payable +50');
ok(Math.abs(after.cash - before.cash - 1050) < 0.01, 'expected cash in drawer +1,050 (the cash one only)');
await ev(() => go('#/closing')); await P.waitForTimeout(700);
ok(/Other income \(profit\)/.test(await P.textContent('#view')) && /Scrap sale/.test(await P.textContent('#view')), 'month-end P&L shows other income by type');
await P.screenshot({ path: '/tmp/pgt/l2/shots/v35-closing.png' });
await ev(() => go('#/reports')); await P.waitForTimeout(700);
ok(/Other income/.test(await P.textContent('#view')) && /other income \+ 3,500/.test(await P.textContent('#view')), 'Reports & P&L: column + tile hint');
ok(/Output VAT \(invoices \+ other income\)/.test(await P.textContent('#view')), 'VAT summary includes other income VAT');
const adv = await ev(() => ROLES.advisor.pages.includes('incomes'));
ok(!adv, 'Service Advisor cannot open Other income (same as expenses)');

console.log('\nPlain quotation / invoice');
const q = await ev(() => S.quotes[0].id), inv = await ev(() => S.invoices[0].id);
const html0 = await ev(id => docHTML('invoice', get('invoices', id)), inv);
ok(/logo\.svg/.test(html0) && /TRN:/.test(html0), 'normal invoice has logo + TRN line');
await ev(id => go('#/invoice/' + id), inv); await P.waitForTimeout(700);
ok(!!(await P.$('#plain_invoice')), 'invoice page has the "Plain document" tick box');
await P.click('#plain_invoice'); await P.waitForTimeout(700);
await P.screenshot({ path: '/tmp/pgt/l2/shots/v35-plain-tick.png' });
ok(await ev(id => get('invoices', id).plain === true, inv), 'tick saved on the invoice');
const st = await ev(() => ({ n: S.settings.garageName, p: brandPhones(), e: S.settings.email, iban: S.settings.wioIban, legal: S.settings.legalName, foot: brandFooterNote() }));
const html1 = await ev(id => docHTML('invoice', get('invoices', id)), inv);
const leaks = [st.n, st.e, st.iban, st.legal, 'mendtech', 'logo.svg', 'watermark', 'TRN:', 'TAX INVOICE', st.foot].filter(x => x && html1.toLowerCase().includes(String(x).toLowerCase()));
ok(leaks.length === 0, 'plain invoice HTML: no company name, logo, watermark, TRN, bank, e-mail or footer', leaks);
ok(/INVOICE/.test(html1) && /Amount in words/.test(html1), 'still a full invoice (items, totals, amount in words)');
await ev(id => previewDoc('invoice', get('invoices', id)), inv); await P.waitForTimeout(1200);
await P.screenshot({ path: '/tmp/pgt/l2/shots/v35-plain-invoice.png' });
await ev(() => closeAllModals());
// PDF: record every text drawn and every image placed
const pdf = await ev(async id => {
  await ensurePdfLibs();
  const texts = [], imgs = [];
  const J = window.jspdf.jsPDF.API, i0 = J.addImage, bp = window.brandPDF;
  J.addImage = function (...a) { imgs.push(a[5] || 'img'); return i0.apply(this, a); };
  window.brandPDF = o => { const B = bp(o), t0 = B.pdf.text; B.pdf.text = (t, ...a) => { texts.push([].concat(t).join(' ')); return t0(t, ...a); }; return B; };
  const d = get('invoices', id); const p1 = buildPDF('invoice', d); const plainT = texts.splice(0), plainI = (p1.output().match(/\/Subtype \/Image/g) || []).length;
  d.plain = false; const p2 = buildPDF('invoice', d); const normT = texts.splice(0), normI = (p2.output().match(/\/Subtype \/Image/g) || []).length; d.plain = true;
  J.addImage = i0; window.brandPDF = bp;
  return { plainT: plainT.join(' | '), plainI, normT: normT.join(' | '), normI, name: pdfName('invoice', d) };
}, inv);
const pleaks = [st.n, st.e, st.iban, 'mendtech', 'TRN:', 'TAX INVOICE', st.foot, (st.p || '').slice(0, 12)].filter(x => x && pdf.plainT.toLowerCase().includes(String(x).toLowerCase()));
ok(pleaks.length === 0 && pdf.plainI === 0, 'plain invoice PDF: no company text, no logo, no watermark', { pleaks, imgs: pdf.plainI });
ok(pdf.normI >= 2 && /TRN:/.test(pdf.normT), 'normal PDF unchanged (logo + TRN)');
ok(!/mendtech/i.test(pdf.name), 'PDF file name has no company name: ' + pdf.name);
await ev(id => go('#/quote/' + id), q); await P.waitForTimeout(700);
await P.click('#plain_quote'); await P.waitForTimeout(600);
const qh = await ev(id => docHTML('quote', get('quotes', id)), q);
ok(!/mendtech|logo\.svg|watermark/i.test(qh) && /QUOTATION/.test(qh) && /Prepared by</.test(qh), 'plain quotation: no company details, "Prepared by" without the name');
const subj = await ev(id => { const d = get('quotes', id); return `${docTitle('quote', d)} ${d.number}${d.plain ? '' : ' — ' + brandFor(d)}`; }, q);
ok(!/MendTech/i.test(subj), 'e-mail subject has no company name');
await P.click('#plain_quote'); await P.waitForTimeout(500);
ok(/logo\.svg/.test(await ev(id => docHTML('quote', get('quotes', id)), q)), 'untick → normal branded quotation again');
ok(errs.length === 0, 'no script errors', errs.slice(0, 5));
console.log(`\n${pass} passed, ${fail} failed`);
await b.close(); process.exit(fail ? 1 : 0);
