import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ok = (c, m, x) => { console.log((c ? 'PASS ' : 'FAIL ') + m + (c || x === undefined ? '' : ' ' + JSON.stringify(x).slice(0, 300))); if (!c) process.exitCode = 1; };
const errs = []; const P = await (await b.newContext({ viewport: { width: 1300, height: 1300 } })).newPage(); P.on('pageerror', e => errs.push(e.message));
await P.goto('http://localhost:8099/new/index.html'); await P.waitForTimeout(2500);
await P.evaluate(() => go('#/technicians')); await P.waitForTimeout(500);
ok(await P.$('[onclick="wageReceipt()"]'), 'Technicians page: Wage receipt button');
const t = await P.evaluate(() => S.technicians[0].name);
await P.click('[onclick="wageReceipt()"]'); await P.waitForTimeout(400);
await P.fill('.modal [name=basic], .modal #f_basic', '2500').catch(() => {});
const ids = await P.evaluate(() => [...document.querySelectorAll('.modal input, .modal select')].map(i => i.id || i.name));
await P.evaluate(() => { const set = (k, v) => { const el = document.querySelector(`.modal [id$="${k}"]`) || document.querySelector(`.modal [name="${k}"]`); el.value = v; }; set('basic', '2500'); set('additional', '300'); set('addNote', '20 h overtime'); set('deduction', '500'); set('dedNote', 'advance paid 12 Oct'); });
await P.click('.modal [data-save]'); await P.waitForTimeout(1200);
const doc = await P.evaluate(() => (document.querySelector('.modal .bdoc') || {}).innerText || '');
ok(/WAGE RECEIPT/.test(doc) && /2,300\.00/.test(doc) && /20 h overtime/.test(doc) && /advance paid 12 Oct/.test(doc) && doc.includes(`I, ${'X'}`.replace('X', '')), 'receipt shows wages, extra, deduction, net 2,300', { ids, doc: doc.slice(0, 600) });
ok(doc.includes('signature'), 'signature line for the technician');
await (await P.$('.modal .bdoc')).screenshot({ path: '/tmp/pgt/t/wage/receipt.png' });
const exp = await P.evaluate(() => S.expenses.find(e => e.wage));
ok(exp && exp.amount === 2300 && exp.category === 'Salaries & Wages' && exp.wage.number === 'WR-0001', 'recorded as a Salaries & Wages expense', exp);
await P.evaluate(() => closeAllModals());
await P.evaluate(id => editExpense(id), exp.id); await P.waitForTimeout(400);
const btn = await P.$('.modal button:has-text("Wage receipt")'); ok(!!btn, 'expense has a reprint button');
await btn.click(); await P.waitForTimeout(500);
ok(/WAGE RECEIPT/.test(await P.evaluate(() => document.querySelector('.modal .bdoc').innerText)), 'reprint works');
await P.setViewportSize({ width: 390, height: 800 }); await P.waitForTimeout(400);
ok(await P.evaluate(() => document.documentElement.scrollWidth <= 392), 'fits a phone');
ok(!errs.length, 'no page errors', errs);
await b.close();
